window.MealTrackerData = {
  storageKey: "office-meal-tracker-v3",
  employees: [
    { name: "Nusha Farin Islam", role: "QA" },
    { name: "Nafi Afia Zahin", role: "QA" },
    { name: "Meskat Mujahidi", role: "QA" },
    { name: "Hedaetul Islam", role: "QA" },
    { name: "Fariba Tabassum", role: "QA" },
    { name: "Fokrul Islam Bhuiyan", role: "QA" },
    { name: "Mohammed Aarafat Uddin", role: "QA" },
    { name: "Syed Irfan Kayum", role: "QA" },
    { name: "Sadia Afrin", role: "QA" },
    { name: "S. M. Rakib- Ul- Islam", role: "Dev" },
    { name: "Sk. Wasiqul Hoque", role: "QA" },
    { name: "Riasat Haque", role: "QA" },
    { name: "Md. Rabbi Islam Sajid", role: "QA" },
    { name: "Sakif Al Faruque", role: "QA" },
    { name: "Maisha Shams", role: "QA" },
    { name: "Naoshin Anzum Hridi", role: "QA" },
    { name: "Mahir Ahmed Niloy", role: "QA" },
    { name: "Dhruba Nandi", role: "QA" },
    { name: "Tanmay Bhowmik", role: "QA" },
    { name: "Zahra Zannat", role: "QA" },
    { name: "Md. Al-Amin Hossain", role: "Dev" },
    { name: "MD. ROKIBUL HASAN", role: "Dev" },
    { name: "Ahammed Hossain Shanto", role: "Dev" },
    { name: "MD Mostasim Billah", role: "Dev" },
    { name: "Shahriar Saleque", role: "Dev" },
    { name: "Md. Shahibur Rahman", role: "Dev" },
    { name: "Md. Muzahidul Islam", role: "Dev" },
    { name: "Moshiur Rahman", role: "Dev" },
    { name: "Dipu Ram Roy", role: "Dev" },
    { name: "Md. Mubinur Rahman", role: "Dev" },
    { name: "Md. Gul Jamal Zim", role: "Dev" },
    { name: "Tasfik Rahman", role: "Dev" },
    { name: "Subrata Roy", role: "Dev" },
    { name: "Md. Ashraful Islam", role: "Dev" },
    { name: "Partha Sarker", role: "Dev" },
    { name: "Md Ashaduzzaman", role: "Dev" },
    { name: "Abdun Naser Tahiyat", role: "Dev" },
    { name: "Md Jobaer Hassan", role: "Dev" },
    { name: "Md. Yusuf", role: "Dev" },
    { name: "Md. Habibur Rahman", role: "Dev" },
    { name: "Nazmus Saif", role: "Dev" },
    { name: "Imran Khan", role: "Dev" },
    { name: "NOWROSE IRAB POLL", role: "Dev" },
    { name: "T. H. Riyadh", role: "Dev" },
    { name: "RAKIBUL ISLAM RAFI", role: "Dev" },
    { name: "Rimi Reza", role: "Dev" },
    { name: "MUHAMMAD SADRUL MUTTAQUIN HOQUE NAJAT", role: "Dev" },
    { name: "FARHAN FEROZ AUSHI", role: "Dev" },
    { name: "Ragib Hassan", role: "Dev" },
    { name: "Ananta Akash Podder", role: "Dev" },
    { name: "Md Arafat Rahman", role: "Dev" },
    { name: "Nayeem Hasan Anik", role: "Dev" },
    { name: "Md. Rezaul Islam", role: "Dev" },
    { name: "Mahmudul Hasan", role: "Dev" },
    { name: "Hasan Al Mamun", role: "Dev" },
    { name: "Nafis Sazid", role: "Dev" },
    { name: "Md. Redwanul Karim", role: "Dev" },
    { name: "Saadman Sakib", role: "Dev" },
    { name: "Saiful Islam", role: "Bookkeeper" },
    { name: "Zakir Ahmad", role: "PM" },
    { name: "Nahid Hasan", role: "PM" },
    { name: "Samiul Alam", role: "BPM" },
    { name: "Sohana Akter", role: "CSR" },
    { name: "Md. Mahmud Hasan", role: "IT" },
    { name: "Joynal Abedin", role: "IT" },
    { name: "Ayesha Sirajee Leena", role: "HR" },
    { name: "Miskat", role: "HR" },
    { name: "Md Mahfuz Ibne Ali Ayon", role: "Intern" },
    { name: "Md. Jariful Rahman Ovi", role: "Intern" },
    { name: "Md. Nahidur Rahman Nahid", role: "Intern" },
    { name: "Ashraful Islam Opu", role: "QA" },
    { name: "Muntasir Mahmud Amit", role: "QA" },
    { name: "Mehrab Hasan", role: "QA" },
  ],
  jobRoles: ["QA", "Dev", "Bookkeeper", "PM", "BPM", "CSR", "IT", "HR", "Intern", "Other"],
  workStatuses: ["Work from Office", "Work from Home", "Leave"],
};
